import { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import Header from '../components/header';
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Meera Car rental",
  description: "Generated by G21",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
